### ISSUE TITLE
推荐一个分布式锁demo

### ISSUE THREAD

**Issue by mrpre** [alibaba/TairString#1]
https://github.com/aliyun/alibabacloud-tairjedis-sdk/blob/master/src/test/java/com/aliyun/tair/tests/example/DistributeLock.java

**Comment by chenyang8094** [comment]
> https://github.com/aliyun/alibabacloud-tairjedis-sdk/blob/master/src/test/java/com/aliyun/tair/tests/example/DistributeLock.java

thx:)
