### ISSUE TITLE
[Suggest] RedisModule command func should return REDISMODULE_OK

### ISSUE THREAD

**Issue by sundb** [alibaba/TairString#2]
[https://redis.io/topics/modules-api-ref](https://redis.io/topics/modules-api-ref)

The command function type is the following:
```
 int MyCommand_RedisCommand(RedisModuleCtx *ctx, RedisModuleString **argv, int argc);
```
And is supposed to always return REDISMODULE_OK.

**Comment by baronwangr** [comment]
Thanks for the kind reminder, we will fix it accordingly.

**Comment by chenyang8094** [comment]
> https://redis.io/topics/modules-api-ref
> 
> The command function type is the following:
> 
> ```
>  int MyCommand_RedisCommand(RedisModuleCtx *ctx, RedisModuleString **argv, int argc);
> ```
> 
> And is supposed to always return REDISMODULE_OK.

Thank you for your suggestion. I have also seen the relevant documents. But I personally don't understand the recommendations of the official documentation too much. For the module, it seems strange that `REDISMODULE_OK` is still returned if there is an error in the cmd. What do you think?

**Comment by sundb** [comment]
@chenyang8094 I've been wondering about the REDISMODULE_OK convention for a long time, and there's no documentation on why it's done.
But it is clear from the existing code that when REDISMODULE_ERR is returned, there must be a serious problem, such as permission, using an illegal interface (e.g. the key of ListPush is not OBJ_LIST).
Maybe RedieModule should add error statistics, developers can analyze the problem based on these error statistics (this is just my guess).
